# Generated by Django 5.1.2 on 2024-12-10 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_author_biography'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='biography',
        ),
    ]
